apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-kustomize-argoapp
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: site=iamraj007/mynginx
    argocd-image-updater.argoproj.io/site.update-strategy: latest
    argocd-image-updater.argoproj.io/git-branch: main                     
    argocd-image-updater.argoproj.io/site.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iamraj007/argocd_apps.git
    targetRevision: HEAD
    path: apps/mynginx-webapp/web/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
