apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: corp-kustomize-argoapp-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: corpimg=iamraj007/webdemo
    argocd-image-updater.argoproj.io/corpimg.update-strategy: digest
    #    argocd-image-updater.argoproj.io/corpimg.update-strategy: latest
    #    argocd-image-updater.argoproj.io/corpimg.allow-tags: regexp:^latest
    argocd-image-updater.argoproj.io/git-branch: main                     
    argocd-image-updater.argoproj.io/corpimg.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/corpimg.pull-secret: pullsecret:argocd/acr
spec:
  project: default
  source:
    repoURL: https://github.com/iamraj007/argocd_apps.git
    targetRevision: HEAD
    path: apps/corpapp/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: corp-kustomize-argoapp-test
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: corpimg=iamraj007/webdemo
    argocd-image-updater.argoproj.io/corpimg.update-strategy: digest
    argocd-image-updater.argoproj.io/corpimg.force-update: "true"
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/corpimg.pull-secret: pullsecret:argocd/acr
spec:
  project: default
  source:
    repoURL: https://github.com/iamraj007/argocd_apps.git
    targetRevision: HEAD
    path: apps/corpapp/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
