apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-site
  template:
    metadata:
      labels:
        app: my-site
    spec:
      containers:
      - image: iamraj007/site:v1
        name: site-front-container-app
        ports:
        - containerPort: 80
          protocol: TCP
