apiVersion: apps/v1
kind: Deployment
metadata:
  name: corpapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-corpapp
  template:
    metadata:
      labels:
        app: my-corpapp
    spec:
      containers:
      - image: planethomeregistry.azurecr.io/webpoc:latest
        name: corpapp-front-container-app
        ports:
        - containerPort: 80
          protocol: TCP
