apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev  

commonLabels:
  myenv: my-nginx-frontendapp

resources:
 - ns.yaml
 - ../../../my-nginx-app/base/

patchesStrategicMerge:
- deployment_app.yaml
- replica-and-rollout-strategy.yaml

images:
- name: iamraj007/my-nginx
  newTag: devv2

nameSuffix: -dev
namePrefix: mycompany-


