apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
commonLabels:
  myenv: my-corpapp-frontendapp
resources:
- ns.yaml
- ../../../corpapp/base/
patchesStrategicMerge:
- deployment_app.yaml
- replica-and-rollout-strategy.yaml
images:
- name: planethomeregistry.azurecr.io/webpoc
  digest: sha256:8091994c72a50c01d36b9b9c579d271ed9e27d9a54146c4c6c191587bf6b3212
nameSuffix: -devenv
namePrefix: mycorpapp-
