apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitops-nginx
  name: gitops-svc
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 5000
  selector:
    app: gitops-nginx
