apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - image: iamraj007/mynginx:v2
        name: web-front-container-app
        ports:
        - containerPort: 80
          protocol: TCP
